name: Generate images.json

on:
  push:
    paths:
      - 'assets/wines/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          mkdir -p data

          echo "[" > data/images.json

          first=true

          ls assets/wines | grep -v ".keep" | sort | while IFS= read -r file
          do
            if [ "$first" = true ]; then
              echo "  \"$file\"" >> data/images.json
              first=false
            else
              echo "  ,\"$file\"" >> data/images.json
            fi
          done

          echo "]" >> data/images.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/images.json
          git commit -m "auto: update images.json" || echo "no changes"
          git push
