name: Generate images.json

on:
  push:
    paths:
      - assets/wines/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          mkdir -p data
          echo "[" > data/images.json

          for file in assets/wines/*; do
            filename=$(basename "$file")
            if [ "$filename" != ".keep" ]; then
              echo "  \"$filename\"," >> data/images.json
            fi
          done

          sed -i '$ s/,$//' data/images.json
          echo "]" >> data/images.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/images.json
          git commit -m "auto images.json" || echo "no changes"
          git push
